---
services:
  kakao-be:
    image: kakao-be:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: kakao-be
    networks:
      - coupon-network
    ports:
      -  "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://coupon-mysql:3306/coupon
      - SPRING_DATASOURCE_USERNAME=abcd
      - SPRING_DATASOURCE_PASSWORD=1234

networks:
  coupon-network:
    name: coupon-network  # 명시적으로 네트워크 이름 설정
    external: true        # Compose가 해당 네트워크를 외부 네트워크로 인식하도록 설정