server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  application:
    name: kakao-be
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://coupon-mysql:3306/coupon
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: abcd
    password: 1234
  data:
    redis:
      host: coupon-redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# prometheus setting
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
