server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  applicaion:
      name: kakao-be
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://coupon-mysql:3306/coupon
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: abcd
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus

logging:
  level:
    '[com.example.kakao]': DEBUG
    '[org.hibernate.type]': TRACE
